from customer_analyzer import  CustomerAnalyzer


def main():
    customer_analyzer_obj = CustomerAnalyzer(
      cols=['COUNTRY', 'LE_BOOK', 'FAX_NUMBER_1',
       'FAX_NUMBER_2', 'NAICS_CODE', 'SSN_NUMBER', 'HEALTH_INSURANCE_NUMBER',
       'EMP_ADDRESS_1', 'EMP_ADDRESS_2', 'EMP_VILLAGE', 'EMP_COUNTRY',
       'WORK_TELEPHONE', 'ECONOMIC_SECTOR_CODE', 'VISION_SBU',
       'CUSTOMER_GENDER', 'LEGAL_STATUS', 'ACCOUNT_OPENING_MODE',
       'DATE_OF_BIRTH', 'MARITAL_STATUS', 'NEXT_OF_KIN_ID_TYPE',
       'COMM_RESIDENCE_TYPE', 'EDUCATION',
       'RELATED_PARTY', 'INTERNET_BANKING_SUBSCRIPTION','MOBILE_BANKING_SUBSCRIPTION', 
       'OCCUPATION', 'FORENAME_1', 'FORENAME_2', 'SURNAME', 'CUSTOMER_ACRONYM',
       'SALUTATION', 'VISION_OUC', 'ACCOUNT_OFFICER', 'CUSTOMER_OPEN_DATE', 
       'PLACE_OF_BIRTH', 'SPOUSE_NAME', 'SOCIAL_ECONOMIC_CLASS', 'NEXT_OF_KIN_NAME',
       'NEXT_OF_KIN_ID_NUMBER', 'NEXT_OF_KIN_TELEPHONE', 'NEXT_OF_KIN_EMAIL_ID',
       'NUMBER_OF_DEPENDANTS', 'ACCOUNT_MANDATE_NAME', 'ACCOUNT_MANDATE_ID_TYPE',
       'ACCOUNT_MANDATE_ID_NUMBER', 'NATIONALITY', 'RESIDENCE',
       'COMM_ADDRESS_1', 'COMM_ADDRESS_2', 'COMM_VILLAGE', 'COMM_COUNTRY',
       'PERM_ADDRESS_1', 'PERM_ADDRESS_2', 'PERM_VILLAGE', 'PERM_COUNTRY',
       'EMAIL_ID', 'HOME_TELEPHONE', 'CUSTOMER_TIN', 'RELATED_PARTY_NAME',
       'LOCAL_GOVT_MEMBER', 'OCCUPATION', 'EMPLOYER_NAME', 'EMPLOYEE_ID',
       'INCOME', 'INCOME_FREQUENCY', 'CUSTOMER_STATUS', 'RELATIONSHIP_TYPE',
       'NATIONAL_ID_TYPE', 'NATIONAL_ID_NUMBER', 'GROUP_NAME', 'GROUP_NUMBER',
       'DATE_LAST_MODIFIED',
      'INTERNET_BANKING_SUBSCRIPTION', 'MOBILE_BANKING_SUBSCRIPTION', 
       'CUSTOMER_NAME'
      ],
      file_checked="CUSTOMER",
      test_iter="ITERATION 1",
      source_name="T24",
      destination_name="SUNOID",
      identifier="CUSTOMER_ID"
    )
  
    customer_analyzer_obj.load_destination_data()
    customer_analyzer_obj.load_source_data()
    customer_analyzer_obj.check_accuracy()
    customer_analyzer_obj.export_exceptions()

if __name__ == "__main__":
  main()